name: astramind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^5.1.0
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^2.0.1

  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/